version: "2.4"

services:
  producer:
    image: arielguillendev/nest-rmq-example-producer
    build:
      context: .
      args:
        - APP=producer
    env_file:
        - .env
    ports:
      - "4000:4000"
  consumer-1:
    image: arielguillendev/nest-rmq-example-consumer-1
    build:
      context: .
      args:
        - APP=consumer-1
    env_file:
      - .env
  consumer-2:
      image: arielguillendev/nest-rmq-example-consumer-2
      build:
        context: .
        args:
          - APP=consumer-2
      env_file:
        - .env